### ISSUE TITLE
The module freezes server after install

### ISSUE THREAD

**Issue by flancer64** [flancer32/mage2_ext_csp#4]
[This case](https://github.com/flancer32/mage2_ext_csp/issues/2#issuecomment-636279269)

**Comment by flancer64** [comment]
> Hi, I tested it, this is the result:
Command 'fl32:csp:analyze': Analyze CSP violation reports and compose policy rules. 3 rules were added. 3 reports were deleted (id: 1-3). Command 'fl32:csp:analyze' is completed.
but the sites are going in timeout again, could it be a conflict with other extensions?

I think that 3 reports is too few to freeze server and both sites. So, high load shoud not be the reason.

**Comment by Joso** [comment]
OK, flancer64, 
Can you tell me the steps to follow based on the tests already carried out?

do you need to know which extensions are installed on the site?

**Comment by flancer64** [comment]
There is configuration option `fl32_csp/general/enabled`. It is enabled by default. You can disable it.
```
INSERT INTO core_config_data  (`scope`, scope_id, `path`, value) VALUES ('default', 0, 'fl32_csp/general/enabled', '0');
```

Insert, please, this configuration option to DB then try to install module again.

**Comment by flancer64** [comment]
@Joso, in what mode you M2 app is when you install `flancer32/mage2_ext_csp` - in `developer` or in `production` mode?

I think you should try to switch Magento 2 application to developer mode, then install ext, then switch back to production mode:
```
$ ./bin/magento deploy:mode:set developer
$ composer require flancer32/mage2_ext_csp
$ ./bin/magento deploy:mode:set production
```

**Comment by flancer64** [comment]
> The site hosted on different VPS than the other site. but the system is the same: Debian 9, Plesk obsidian, 8Gb ram.

@Joso , what is the PHP version on your prod?

**Comment by Joso** [comment]
Hi, now I'm installing the module. The site is in production mode with php 7.3.18

**Comment by Joso** [comment]
> @Joso, in what mode you M2 app is when you install `flancer32/mage2_ext_csp` - in `developer` or in `production` mode?
> 
> I think you should try to switch Magento 2 application to developer mode, then install ext, then switch back to production mode:
> 
> ```
> $ ./bin/magento deploy:mode:set developer
> $ composer require flancer32/mage2_ext_csp
> $ ./bin/magento deploy:mode:set production
> ```

ok, now follow this indication

**Comment by Joso** [comment]
Well, after installation in develop mode, and  change in production mode: 
```
bin/magento module:status --disabled
Flancer32_Base
Flancer32_Csp
```
The sites run

**Comment by flancer64** [comment]
OK. Could you disable modules using [config option](https://github.com/flancer32/mage2_ext_csp/issues/4#issuecomment-636287678) `fl32_csp/general/enabled` then enable Magento modules `Flancer32_Base` 
```
$ bin/magento module:enable Flancer32_Base`
```
check the sites and then enable `Flancer32_Csp`
```
$ bin/magento module:enable Flancer32_Csp
```

then check the sites again?

If sites will be alive, please, try to enable CSP-module functionality  using adminhtml.

**Comment by Joso** [comment]
First step:

The following modules have been enabled:
- Flancer32_Base
```

To make sure that the enabled modules are properly registered, run 'setup:upgrade'.
Cache cleared successfully.
Generated classes cleared successfully. Please run the 'setup:di:compile' command to generate classes.
Info: Some modules might require static view files to be cleared. To do this, run 'module:enable' with the --clear-static-content option to clear them.

```
Now run `setup:upgrade` or enable the second module?

**Comment by flancer64** [comment]
`setup:upgrade` will create DB schemas elements (tables). If you have fl32csp table in DB I suppose you can enable second module.

**Comment by flancer64** [comment]
Did you check sites availability after the frist module installation?

**Comment by Joso** [comment]
> Did you check sites availability after the frist module installation?

Yes the sites run in this time. I report you after to enable the module

**Comment by flancer64** [comment]
I think the better way is to enable/disable & re-configure modules in `developer` mode and to switch to `production` mode at the end (if sites will be alive at the end).

**Comment by Joso** [comment]
therefore, the module must be installed in developer mode. Then change to production mode and enable one module at a time and then run `setup: upgrade, compile and develop static content`

is it right?

**Comment by flancer64** [comment]
I think the module should be installed and enabled in `developer` mode and after that Magento app should be switched to `production` mode. These steps should be performed on a clean app:
```
$ ./bin/magento deploy:mode:set developer
$ composer require flancer32/mage2_ext_csp
$ ./bin/magento setup:upgrade
$ ./bin/magento deploy:mode:set production
$ ./bin/magento cache:clean
```

**Comment by Joso** [comment]
> I think the module should be installed and enabled in `developer` mode and after that Magento app should be switched to `production` mode. These steps should be performed on a clean Magento 2 app (w/o `flancer32/mage2_ext_csp` module):
> 
> ```
> $ ./bin/magento deploy:mode:set developer
> $ composer require flancer32/mage2_ext_csp
> $ ./bin/magento setup:upgrade
> $ ./bin/magento deploy:mode:set production
> $ ./bin/magento cache:clean
> ```
> 
> `compile` and `static-content` steps are performed inside `set production` step.

well, I will try with a backup version of the site to redo the whole procedure as indicated. I will report any errors that should occur.
In this way I will be sure that when I install the module on the live site I will have no problems ..

Thanks for your help.
