### ISSUE TITLE
Bug from 2.3.5-p1

### ISSUE THREAD

**Issue by netwolf103** [flancer32/mage2_ext_csp#7]
Exception #0 (Exception): Notice: Undefined index: id in app\code\Magento\Config\Model\Config\Structure\Element\Iterator.php on line 63
Cause: mage2_ext_csp\etc\adminhtml\system.xml miss:
` <tab id="security" translate="label" sortOrder="200"><label>Security</label</tab>`

**Comment by flancer64** [comment]
Fixed in `master` branch. Thanks again.
